# Generated by Django 5.2 on 2025-05-19 09:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='USER', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('for_doctor', models.BooleanField(default=False)),
                ('for_payment', models.BooleanField(default=False)),
                ('for_chat', models.BooleanField(default=False)),
                ('for_sickness', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('date_of_birth', models.DateField(auto_now_add=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.TextField(default='Not specify')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='healthcare.role')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('treatment_history', models.TextField(null=True)),
                ('user', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='md_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('feedback', models.TextField(null=True)),
                ('med_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare.medicalrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalRecordDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('symptoms', models.TextField(null=True)),
                ('diagnosis', models.TextField(null=True)),
                ('treatment_date', models.DateTimeField()),
                ('med_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='med_record', to='healthcare.medicalrecord')),
                ('user', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='mrd_doctor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('instruction', models.TextField(null=True)),
                ('attention', models.TextField(null=True)),
                ('med_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare.medicalrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sickness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('med_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare.medicalrecord')),
                ('status', models.ForeignKey(limit_choices_to={'for_sickness': 1}, on_delete=django.db.models.deletion.CASCADE, to='healthcare.status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RealTimeChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('chat_box', models.TextField(null=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(limit_choices_to={'for_chat': 1}, on_delete=django.db.models.deletion.CASCADE, to='healthcare.status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('method', models.TextField(null=True)),
                ('hospital_fee', models.FloatField(default=0)),
                ('med_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare.medicalrecord')),
                ('status', models.ForeignKey(default=None, limit_choices_to={'for_payment': 1}, on_delete=django.db.models.deletion.CASCADE, to='healthcare.status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiagnosisPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('fromDateTime', models.DateTimeField()),
                ('toDateTime', models.DateTimeField()),
                ('max_requests', models.IntegerField(default=5)),
                ('current_requests', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='dp_doctor', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(default=1, limit_choices_to={'for_doctor': 1}, on_delete=django.db.models.deletion.CASCADE, to='healthcare.status')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
