# Generated by Django 5.2 on 2025-05-19 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosisperiod',
            name='user',
            field=models.ForeignKey(default=3, limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='dp_doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
