# Generated by Django 5.2 on 2025-05-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0002_alter_diagnosisperiod_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosisperiod',
            name='user',
        ),
    ]
