# Generated by Django 5.2 on 2025-05-19 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0003_remove_diagnosisperiod_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
