# Generated by Django 5.2 on 2025-05-19 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0005_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimechat',
            name='status',
            field=models.ForeignKey(default=3, limit_choices_to={'for_chat': 1}, on_delete=django.db.models.deletion.CASCADE, to='healthcare.status'),
        ),
    ]
