# Generated by Django 5.2 on 2025-05-20 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0006_alter_realtimechat_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medication',
            unique_together={('med_record', 'name')},
        ),
    ]
