# Generated by Django 5.2 on 2025-05-20 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0007_alter_medication_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['-id']},
        ),
    ]
