# Generated by Django 5.2 on 2025-05-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0011_alter_evaluation_options_alter_medicalrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosisperiod',
            options={'ordering': ['-id']},
        ),
    ]
