# Generated by Django 5.2 on 2025-05-22 02:28

import healthcare.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0012_alter_diagnosisperiod_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosisperiod',
            name='fromDateTime',
            field=healthcare.models.CustomDateTimeField(),
        ),
        migrations.AlterField(
            model_name='diagnosisperiod',
            name='toDateTime',
            field=healthcare.models.CustomDateTimeField(),
        ),
        migrations.AlterField(
            model_name='medicalrecorddetail',
            name='treatment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=healthcare.models.CustomDateTimeField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=healthcare.models.CustomDateTimeField(auto_now_add=True),
        ),
    ]
