# Generated by Django 5.2 on 2025-05-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0013_alter_diagnosisperiod_fromdatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
    ]
