# Generated by Django 5.2 on 2025-05-22 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0014_alter_user_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
