# Generated by Django 5.2 on 2025-05-22 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0017_alter_diagnosisperiod_fromdatetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisperiod',
            name='user',
            field=models.ForeignKey(default=3, limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='dp_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='healthcare.role'),
        ),
    ]
