# Generated by Django 5.2 on 2025-05-22 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0018_diagnosisperiod_user_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['-id']},
        ),
        migrations.AlterUniqueTogether(
            name='medication',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='med_record',
        ),
        migrations.RemoveField(
            model_name='medicalrecorddetail',
            name='treatment_date',
        ),
        migrations.RemoveField(
            model_name='medicalrecorddetail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='med_record',
        ),
        migrations.RemoveField(
            model_name='sickness',
            name='med_record',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='record_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='healthcare.medicalrecorddetail'),
        ),
        migrations.AddField(
            model_name='medicalrecorddetail',
            name='diagnosis_period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_date', to='healthcare.diagnosisperiod'),
        ),
        migrations.AddField(
            model_name='medication',
            name='record_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='healthcare.medicalrecorddetail'),
        ),
        migrations.AddField(
            model_name='payment',
            name='record_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='healthcare.medicalrecorddetail'),
        ),
        migrations.AddField(
            model_name='sickness',
            name='record_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='healthcare.medicalrecorddetail'),
        ),
        migrations.AlterField(
            model_name='diagnosisperiod',
            name='user',
            field=models.ForeignKey(default=3, limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalrecorddetail',
            name='med_record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='med_record', to='healthcare.medicalrecord'),
        ),
        migrations.RemoveField(
            model_name='medication',
            name='med_record',
        ),
    ]
