# Generated by Django 5.2 on 2025-05-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0019_alter_medication_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
