# Generated by Django 5.2 on 2025-05-22 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0020_alter_medication_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
