# Generated by Django 5.2 on 2025-05-22 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0022_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosisperiod',
            name='user',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
