# Generated by Django 5.2 on 2025-05-22 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0025_alter_diagnosisperiod_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosisperiod',
            name='user',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
