# Generated by Django 5.2 on 2025-05-22 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0027_alter_diagnosisperiod_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecorddetail',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='medicalrecorddetail',
            unique_together={('med_record', 'diagnosis_period')},
        ),
    ]
