# Generated by Django 5.2 on 2025-05-24 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0028_alter_medicalrecorddetail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecorddetail',
            name='diagnosis_period',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_date', to='healthcare.diagnosisperiod'),
        ),
    ]
