# Generated by Django 5.2 on 2025-05-25 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0029_alter_medicalrecorddetail_diagnosis_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecorddetail',
            name='med_record',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='med_record', to='healthcare.medicalrecord'),
        ),
    ]
