# Generated by Django 5.2 on 2025-05-26 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0031_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosisperiod',
            name='status',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'for_doctor': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthcare.status'),
        ),
    ]
