# Generated by Django 5.2 on 2025-05-26 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0032_alter_diagnosisperiod_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosisperiod',
            name='user',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'role': 3}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
